name: Coding Standard

on:
  pull_request:
  push:

jobs:
  coding-standard:
    name: Coding Standard
    uses: brick/coding-standard/.github/workflows/coding-standard.yml@v1
    with:
      working-directory: "tools/ecs"
